vim.o.termguicolors = true
vim.g.colors_name = "xcode-doom"

local c = require("xcode_theme").get_colors()
local transparent = vim.g.xcode_doom_transparent == true
local bg_main = transparent and "NONE" or c.bg
local bg_alt = transparent and "NONE" or c.bg_alt
local bg_base2 = transparent and "NONE" or c.base2
local bg_base1 = transparent and "NONE" or c.base1
local bg_visual = transparent and "NONE" or c.visual
local bg_highlight = transparent and "NONE" or c.bg_highlight

local function hl(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- ============================================================================
-- Core UI (Matches M.polish_hl.defaults)
-- ============================================================================
hl("Normal", { fg = "#ffffff", bg = bg_main })
hl("NormalNC", { fg = "#ffffff", bg = bg_main })
hl("NormalFloat", { fg = "#ffffff", bg = bg_alt })
hl("FloatBorder", { fg = "#3f4040", bg = bg_alt })
hl("ColorColumn", { bg = bg_base2 })
hl("Cursor", { fg = "#292A30", bg = "#5DD8FF" })
hl("CursorLine", { bg = bg_base2 })
hl("CursorColumn", { bg = bg_base2 })
hl("LineNr", { fg = "#5c5e5e" })
hl("CursorLineNr", { fg = "#FD8F3F", bold = true })
hl("SignColumn", { fg = "#ffffff", bg = bg_main })
hl("StatusLine", { fg = "#ffffff", bg = bg_base2 })
hl("StatusLineNC", { fg = "#969896", bg = bg_base1 })
hl("WinSeparator", { fg = "#3f4040" })
hl("VertSplit", { fg = "#3f4040" })
hl("Pmenu", { fg = "#969896", bg = bg_alt })
hl("PmenuSel", { fg = "#ffffff", bg = bg_highlight, bold = true })
hl("PmenuSbar", { bg = bg_base2 })
hl("PmenuThumb", { bg = "#5c5e5e" })
hl("Visual", { bg = bg_visual })
hl("Search", { fg = "#292A30", bg = "#D0BF68" })
hl("IncSearch", { fg = "#292A30", bg = "#FD8F3F" })
hl("MatchParen", { fg = "#ffffff", bg = "#292b2b", bold = true })
hl("Folded", { fg = "#969896", bg = bg_base1 })
hl("FoldColumn", { fg = "#969896", bg = bg_main })
hl("NonText", { fg = "#3f4040" })
hl("Whitespace", { fg = "#3f4040" })
hl("EndOfBuffer", { fg = bg_main })

-- ============================================================================
-- Syntax (Matches M.polish_hl.syntax)
-- ============================================================================
hl("Comment", { fg = "#6C7986", italic = true })
hl("Constant", { fg = "#A167E6" })
hl("String", { fg = "#FC6A5D" })
hl("Character", { fg = "#FC6A5D" })
hl("Number", { fg = "#D0BF68" })
hl("Boolean", { fg = "#A167E6", bold = true })
hl("Float", { fg = "#D0BF68" })
hl("Identifier", { fg = "#41A1C0" })
hl("Function", { fg = "#D0A8FF" })
hl("Statement", { fg = "#FC5FA3", bold = true })
hl("Conditional", { fg = "#FC5FA3", bold = true })
hl("Repeat", { fg = "#FC5FA3", bold = true })
hl("Label", { fg = "#FC5FA3" })
hl("Operator", { fg = "#FD8F3F" })
hl("Keyword", { fg = "#FC5FA3", bold = true })
hl("Exception", { fg = "#FC5FA3" })
hl("PreProc", { fg = "#FD8F3F" })
hl("Include", { fg = "#FD8F3F" })
hl("Define", { fg = "#FD8F3F" })
hl("Macro", { fg = "#FD8F3F" })
hl("Type", { fg = "#5DD8FF" })
hl("StorageClass", { fg = "#5DD8FF" })
hl("Structure", { fg = "#5DD8FF" })
hl("Typedef", { fg = "#5DD8FF" })
hl("Special", { fg = "#FD8F3F" })
hl("SpecialChar", { fg = "#FD8F3F" })
hl("Tag", { fg = "#FD8F3F" })
hl("Delimiter", { fg = "#FD8F3F" })
hl("SpecialComment", { fg = "#6C7986" })
hl("Debug", { fg = "#FC6A5D" })

-- ============================================================================
-- Treesitter (Matches M.polish_hl.treesitter)
-- ============================================================================
hl("@variable", { fg = "#41A1C0" })
hl("@variable.builtin", { fg = "#9EF1DD" })
hl("@variable.parameter", { fg = "#59B0CF" })
hl("@variable.member", { fg = "#41A1C0" })
hl("@variable.member.key", { fg = "#41A1C0" })
hl("@constant", { fg = "#A167E6" })
hl("@constant.builtin", { fg = "#A167E6" })
hl("@constant.macro", { fg = "#FD8F3F" })
hl("@comment", { link = "Comment" })
hl("@string", { link = "String" })
hl("@string.escape", { fg = "#FD8F3F" })
hl("@string.regex", { fg = "#FD8F3F" })
hl("@character", { link = "Character" })
hl("@number", { link = "Number" })
hl("@number.float", { link = "Number" })
hl("@boolean", { link = "Boolean" })
hl("@float", { link = "Float" })
hl("@field", { fg = "#41A1C0" })
hl("@property", { fg = "#41A1C0" })
hl("@function", { link = "Function" })
hl("@function.builtin", { fg = "#9EF1DD" })
hl("@function.macro", { fg = "#FD8F3F" })
hl("@function.call", { fg = "#D0A8FF" })
hl("@function.method", { fg = "#41A1C0" })
hl("@function.method.call", { fg = "#41A1C0" })
hl("@constructor", { fg = "#D0A8FF" })
hl("@keyword", { link = "Keyword" })
hl("@keyword.function", { fg = "#FC5FA3" })
hl("@keyword.return", { fg = "#FC5FA3", bold = true })
hl("@keyword.operator", { fg = "#FD8F3F" })
hl("@keyword.import", { fg = "#FC5FA3" })
hl("@keyword.conditional", { fg = "#FC5FA3" })
hl("@keyword.conditional.ternary", { fg = "#FC5FA3" })
hl("@keyword.repeat", { fg = "#FC5FA3" })
hl("@keyword.storage", { fg = "#FC5FA3" })
hl("@keyword.directive.define", { fg = "#FC5FA3" })
hl("@keyword.directive", { fg = "#FC5FA3" })
hl("@operator", { link = "Operator" })
hl("@reference", { fg = "#ffffff" })
hl("@type", { link = "Type" })
hl("@type.builtin", { fg = "#5DD8FF" })
hl("@type.definition", { fg = "#5DD8FF" })
hl("@namespace", { fg = "#5DD8FF" })
hl("@module", { fg = "#FC5FA3" })
hl("@punctuation.delimiter", { fg = "#FD8F3F" })
hl("@punctuation.bracket", { fg = "#FD8F3F" })
hl("@punctuation.special", { fg = "#FD8F3F" })
hl("@symbol", { fg = "#FC6A5D" })
hl("@tag", { fg = "#FD8F3F" })
hl("@tag.attribute", { fg = "#FD8F3F" })
hl("@tag.delimiter", { fg = "#FD8F3F" })
hl("@text", { fg = "#ffffff" })
hl("@text.emphasis", { fg = "#D0BF68" })
hl("@text.strike", { fg = "#A167E6", strikethrough = true })
hl("@annotation", { fg = "#A167E6" })
hl("@attribute", { fg = "#FD8F3F" })
hl("@error", { fg = "#FC6A5D" })
hl("@definition", { sp = "#969896", underline = true })
hl("@scope", { bold = true })
hl("@markup.heading", { fg = "#D0A8FF", bold = true })
hl("@markup.raw", { fg = "#D0BF68" })
hl("@markup.link", { fg = "#FC6A5D" })
hl("@markup.link.url", { fg = "#D0BF68", underline = true })
hl("@markup.link.label", { fg = "#59B0CF" })
hl("@markup.list", { fg = "#FC6A5D" })
hl("@markup.strong", { bold = true })
hl("@markup.underline", { underline = true })
hl("@markup.italic", { italic = true })
hl("@markup.strikethrough", { strikethrough = true })

-- ============================================================================
-- LSP Semantic Tokens (Matches M.polish_hl.lsp)
-- ============================================================================
hl("@lsp.type.class", { fg = "#5DD8FF" })
hl("@lsp.type.enum", { fg = "#5DD8FF" })
hl("@lsp.type.interface", { fg = "#5DD8FF" })
hl("@lsp.type.struct", { fg = "#5DD8FF" })
hl("@lsp.type.typeParameter", { fg = "#59B0CF" })
hl("@lsp.type.function", { fg = "#D0A8FF" })
hl("@lsp.type.method", { fg = "#41A1C0" })
hl("@lsp.type.property", { fg = "#41A1C0" })
hl("@lsp.type.variable", { fg = "#41A1C0" })
hl("@lsp.type.parameter", { fg = "#59B0CF" })
hl("@lsp.type.enumMember", { fg = "#A167E6" })
hl("@lsp.type.keyword", { fg = "#FC5FA3" })
hl("@lsp.type.namespace", { link = "@namespace" })
hl("@lsp.type.module", { link = "@module" })
hl("@lsp.mod.readonly", { italic = true })
hl("@lsp.mod.deprecated", { strikethrough = true })

-- ============================================================================
-- Diagnostics
-- ============================================================================
hl("DiagnosticError", { fg = "#FC6A5D" })
hl("DiagnosticWarn", { fg = "#D0BF68" })
hl("DiagnosticInfo", { fg = "#5DD8FF" })
hl("DiagnosticHint", { fg = "#59B0CF" })
hl("DiagnosticVirtualTextError", { fg = "#FC6A5D", bg = "NONE", italic = true })
hl("DiagnosticVirtualTextWarn", { fg = "#D0BF68", bg = "NONE", italic = true })
hl("DiagnosticSignError", { fg = "#FC6A5D", bg = "NONE" })
hl("DiagnosticSignWarn", { fg = "#D0BF68", bg = "NONE" })

-- ============================================================================
-- Git (Matches M.polish_hl.git)
-- ============================================================================
hl("DiffAdd", { bg = "#67B7A4" })
hl("DiffChange", { bg = "#D0BF68" })
hl("DiffDelete", { bg = "#FC6A5D" })
hl("MiniDiffSignAdd", { fg = "#67B7A4", bg = "NONE" })
hl("MiniDiffSignChange", { fg = "#D0BF68", bg = "NONE" })
hl("MiniDiffSignDelete", { fg = "#FC6A5D", bg = "NONE" })

-- ============================================================================
-- Plugin Overrides (Consolidated for LazyVim)
-- ============================================================================

-- Mini.files
hl("MiniFilesBorder", { fg = "#3f4040", bg = "NONE" })
hl("MiniFilesBorderModified", { fg = "#D0BF68", bg = "NONE" })
hl("MiniFilesCursorLine", { bg = "#32333a", blend = 30 })
hl("MiniFilesDirectory", { fg = "#5DD8FF", bold = true })
hl("MiniFilesFile", { fg = "#ffffff" })
hl("MiniFilesNormal", { fg = "#ffffff", bg = "NONE" })
hl("MiniFilesTitle", { fg = "#FC5FA3", bold = true, bg = "NONE" })
hl("MiniFilesTitleFocused", { fg = "#D0A8FF", bold = true, bg = "NONE" })

-- Mini.icons
hl("MiniIconsAzure", { fg = "#5DD8FF" })
hl("MiniIconsBlue", { fg = "#A167E6" })
hl("MiniIconsCyan", { fg = "#D0A8FF" })
hl("MiniIconsGreen", { fg = "#67B7A4" })
hl("MiniIconsGrey", { fg = "#6C7986" })
hl("MiniIconsOrange", { fg = "#FD8F3F" })
hl("MiniIconsPurple", { fg = "#D0A8FF" })
hl("MiniIconsRed", { fg = "#FC6A5D" })
hl("MiniIconsYellow", { fg = "#D0BF68" })

-- Noice.nvim
hl("NoiceCmdline", { fg = "#969896", bg = "NONE" })
hl("NoiceCmdlineIcon", { fg = "#D0A8FF" })
hl("NoiceCmdlineIconSearch", { fg = "#D0BF68" })
hl("NoiceCmdlinePopup", { fg = "#969896", bg = "NONE" })
hl("NoiceCmdlinePopupBorder", { fg = "#D0A8FF", bg = "NONE" })
hl("NoiceCmdlinePopupBorderSearch", { fg = "#D0BF68", bg = "NONE" })
hl("NoiceConfirm", { fg = "#969896", bg = "NONE" })
hl("NoiceConfirmBorder", { fg = "#D0A8FF", bg = "NONE" })
hl("NoiceCursor", { fg = "#292A30", bg = "#5DD8FF" })
hl("NoiceMini", { fg = "#969896", bg = "NONE" })
hl("NoicePopup", { fg = "#969896", bg = "NONE" })
hl("NoicePopupBorder", { fg = "#D0A8FF", bg = "NONE" })
hl("NoicePopupmenu", { fg = "#969896", bg = "NONE" })
hl("NoicePopupmenuBorder", { fg = "#D0A8FF", bg = "NONE" })
hl("NoicePopupmenuMatch", { fg = "#D0A8FF", bold = true })
hl("NoicePopupmenuSelected", { fg = "#ffffff", bg = "#34353b", blend = 20 })
hl("NoiceScrollbar", { fg = "#34353b", bg = "NONE" })
hl("NoiceScrollbarThumb", { bg = "#5c5e5e" })
hl("NoiceVirtualText", { fg = "#6C7986", italic = true })

-- Blink.cmp
hl("BlinkCmpMenu", { fg = "#969896", bg = "NONE" })
hl("BlinkCmpMenuBorder", { fg = "#D0A8FF", bg = "NONE" })
hl("BlinkCmpMenuSelection", { fg = "#ffffff", bg = "#34353b" })
hl("BlinkCmpLabel", { fg = "#969896" })
hl("BlinkCmpLabelDeprecated", { fg = "#6C7986", strikethrough = true })
hl("BlinkCmpLabelMatch", { fg = "#D0A8FF", bold = true })
hl("BlinkCmpKind", { fg = "#5DD8FF" })
hl("BlinkCmpKindText", { fg = "#969896" })
hl("BlinkCmpKindMethod", { fg = "#D0A8FF" })
hl("BlinkCmpKindFunction", { fg = "#D0A8FF" })
hl("BlinkCmpKindConstructor", { fg = "#D0A8FF" })
hl("BlinkCmpKindField", { fg = "#41A1C0" })
hl("BlinkCmpKindVariable", { fg = "#41A1C0" })
hl("BlinkCmpKindClass", { fg = "#5DD8FF" })
hl("BlinkCmpKindInterface", { fg = "#5DD8FF" })
hl("BlinkCmpKindModule", { fg = "#FC5FA3" })
hl("BlinkCmpKindProperty", { fg = "#41A1C0" })
hl("BlinkCmpKindUnit", { fg = "#D0BF68" })
hl("BlinkCmpKindValue", { fg = "#FC6A5D" })
hl("BlinkCmpKindEnum", { fg = "#5DD8FF" })
hl("BlinkCmpKindKeyword", { fg = "#FC5FA3" })
hl("BlinkCmpKindSnippet", { fg = "#D0A8FF" })
hl("BlinkCmpKindColor", { fg = "#FD8F3F" })
hl("BlinkCmpKindFile", { fg = "#5DD8FF" })
hl("BlinkCmpKindReference", { fg = "#A167E6" })
hl("BlinkCmpKindFolder", { fg = "#5DD8FF" })
hl("BlinkCmpKindEnumMember", { fg = "#A167E6" })
hl("BlinkCmpKindConstant", { fg = "#A167E6" })
hl("BlinkCmpKindStruct", { fg = "#5DD8FF" })
hl("BlinkCmpKindEvent", { fg = "#5DD8FF" })
hl("BlinkCmpKindOperator", { fg = "#FD8F3F" })
hl("BlinkCmpKindTypeParameter", { fg = "#59B0CF" })
hl("BlinkCmpDoc", { fg = "#969896", bg = "NONE" })
hl("BlinkCmpDocBorder", { fg = "#D0A8FF", bg = "NONE" })
hl("BlinkCmpDocSeparator", { fg = "#3f4040" })

-- Avante.nvim
hl("AvanteTitle", { fg = "#FC5FA3", bold = true, bg = "NONE" })
hl("AvanteReversedTitle", { fg = "#292A30", bg = "#FC5FA3" })
hl("AvanteSubtitle", { fg = "#5DD8FF", bg = "NONE" })
hl("AvanteReversedSubtitle", { fg = "#292A30", bg = "#5DD8FF" })
hl("AvanteThirdTitle", { fg = "#D0A8FF", bg = "NONE" })
hl("AvanteReversedThirdTitle", { fg = "#292A30", bg = "#D0A8FF" })

-- ============================================================================
-- Mini.statusline (Added for Enhanced Look)
-- ============================================================================
hl("MiniStatuslineModeNormal", { fg = c.bg, bg = c.blue, bold = true })
hl("MiniStatuslineModeInsert", { fg = c.bg, bg = c.red, bold = true })
hl("MiniStatuslineModeVisual", { fg = c.bg, bg = c.purple, bold = true })
hl("MiniStatuslineModeReplace", { fg = c.bg, bg = c.orange, bold = true })
hl("MiniStatuslineModeCommand", { fg = c.bg, bg = c.yellow, bold = true })
hl("MiniStatuslineModeOther", { fg = c.bg, bg = c.teal, bold = true })

hl("MiniStatuslineDevinfo", { fg = c.fg_alt, bg = bg_base2 })
hl("MiniStatuslineFilename", { fg = c.fg, bg = bg_base1, bold = true })
hl("MiniStatuslineFileinfo", { fg = c.fg_alt, bg = bg_base2 })
hl("MiniStatuslineInactive", { fg = c.fg_alt, bg = bg_main })
hl("MiniStatuslineUrgent", { fg = c.bg, bg = c.red, bold = true }) 

-- ============================================================================
-- Mini.starter (Dashboard)
-- ============================================================================
local pink_accent = "#FF7DB7"
hl("MiniStarterCurrent", { fg = pink_accent, bold = true })
hl("MiniStarterHeader",  { fg = pink_accent })
hl("MiniStarterItem",    { fg = c.fg })
hl("MiniStarterItemBullet", { fg = pink_accent })
hl("MiniStarterItemPrefix", { fg = pink_accent })
hl("MiniStarterSection", { fg = pink_accent, bold = true })
hl("MiniStarterQuery",   { fg = c.blue }) 
