# ~/.config/fish/config.fish  — versão limpa
# Habilita modo desenvolvedor pro Homebrew no macOS beta
set -Ux HOMEBREW_DEVELOPER 1
set -Ux HOMEBREW_FAKE_MACOS 26.0
set -Ux HOMEBREW_MACOS_VERSION 26.0

# Alias pra rodar brew com segurança em betas
function brewdev
    HOMEBREW_DEVELOPER=1 brew $argv
end

fish_add_path /opt/homebrew/bin
set -gx PATH $HOME/.cargo/bin $PATH
set -gx PATH $PATH $HOME/.npm-global/bin

if status is-interactive
    starship init fish | source
    zoxide init fish | source
    
    # Enhanced autocompletion settings
    set -g fish_complete_path $fish_complete_path ~/.config/fish/completions
    
    # Enable case-insensitive completion
    set -g fish_completion_case_insensitive true
    
    # Enable substring matching for completions
    set -g fish_completion_substring true
    
    # Show completion descriptions
    set -g fish_complete_descriptions true
    
    # Auto-suggestion color
    set -g fish_color_autosuggestion brblack
    
    # Enable tab completion cycling
    bind Tab complete
    bind 'shift-tab' complete-and-search
    
    # FZF integration for enhanced completions
    if command -q fzf
        source /opt/homebrew/Cellar/fzf/0.64.0/shell/key-bindings.fish
    end
end



# ───────── Substituições de CLI (não cobertas por plugins) ─────────
alias cat='bat'
alias find='fd'
alias grep='rg'

# ───────── Navegação rápida ─────────
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# ───────── FZF helpers ─────────
abbr -a ff  'fd | fzf'
abbr -a fcd 'cd (fd -t d | fzf)'
abbr -a vh  'history | fzf'

# ───────── Brew helpers ─────────
abbr -a bi 'brew install'
abbr -a bs 'brew search'
# ───────── Brew helpers (continued) ─────────
abbr -a bup 'brew update && brew upgrade'
abbr -a top 'topgrade'
abbr -a bunn 'brew uninstall'
abbr -a setappdaemon 'launchctl kickstart -k gui/$(id -u)/com.setapp.DesktopClient.SetappAgent'
abbr -a open 'open -a'
abbr -a bri 'brew reinstall'
function clean_raycast_node_dock
    plutil -convert xml1 ~/Library/Preferences/com.apple.dock.plist -o - \
    | sed '/com\.raycast\.macos.*\/node.js/,/<\/dict>/d' \
    | plutil -convert binary1 -o ~/Library/Preferences/com.apple.dock.plist -
    killall Dock
    echo "✅ Ícone do node do Raycast removido do Dock"
end
# Added by OrbStack: command-line tools and integration
# This won't be added again if you remove it.
source ~/.orbstack/shell/init2.fish 2>/dev/null || :
source /Users/tuliopinheirocunha/.op/plugins.sh
alias cyopen "pnpm cypress:open"
alias cyrun "pnpm cypress:run"

# Added by Windsurf - Next
fish_add_path /Users/tuliopinheirocunha/.codeium/windsurf/bin

# Added by Windsurf
fish_add_path /Users/tuliopinheirocunha/.codeium/windsurf/bin
alias pip='python3 -m pip'

# This script was automatically generated by the broot program
# More information can be found in https://github.com/Canop/broot
# This function starts broot and executes the command
# it produces, if any.
# It's needed because some shell commands, like `cd`,
# have no useful effect if executed in a subshell.
function br --wraps=broot
    set -l cmd_file (mktemp)
    if broot --outcmd $cmd_file $argv
        source $cmd_file
        rm -f $cmd_file
    else
        set -l code $status
        rm -f $cmd_file
        return $code
    end
end

set -gx OPENAI_API_KEY "xai-IQZTx6fObb6iRREfWhXjDB5HUVtxzzY3P9wGUkBT0O3ZTK7nQGIkPJM4scFWXV7SXy4pk3dh26cdMfpv"
set -gx XAI_API_KEY "xai-IQZTx6fObb6iRREfWhXjDB5HUVtxzzY3P9wGUkBT0O3ZTK7nQGIkPJM4scFWXV7SXy4pk3dh26cdMfpv"

# bun
set --export BUN_INSTALL "$HOME/.bun"
set --export PATH $BUN_INSTALL/bin $PATH
set -gx SSH_AUTH_SOCK "/Users/tuliopinheirocunha/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
export XAI_API_KEY="xai-IQZTx6fObb6iRREfWhXjDB5HUVtxzzY3P9wGUkBT0O3ZTK7nQGIkPJM4scFWXV7SXy4pk3dh26cdMfpv"

string match -q "$TERM_PROGRAM" "kiro" and . (kiro --locate-shell-integration-path fish)
export PATH="$HOME/.bun/bin:$PATH"

### MANAGED BY RANCHER DESKTOP START (DO NOT EDIT)
set --export --prepend PATH "/Users/tuliopinheirocunha/.rd/bin"
### MANAGED BY RANCHER DESKTOP END (DO NOT EDIT)

# opencode
fish_add_path /Users/tuliopinheirocunha/.opencode/bin

# OpenHands CLI aliases
alias openhands="uvx --python 3.12 --from openhands-ai openhands"
alias oh="uvx --python 3.12 --from openhands-ai openhands"
set -x OPENAI_API_KEY "your-new-key-here"

# pnpm
set -gx PNPM_HOME "/Users/tuliopinheirocunha/Library/pnpm"
if not string match -q -- $PNPM_HOME $PATH
  set -gx PATH "$PNPM_HOME" $PATH
end
# pnpm end
