# cortex-cli-completion-version: 1.0.16+195647.12b246b44150
# Cortex CLI completions for fish shell
complete -c cortex -f

# Options
complete -c cortex -l workdir -s w -d "Working directory"
complete -c cortex -l connection -s c -d "Snowflake connection name"
complete -c cortex -l model -s m -d "Model override"
complete -c cortex -l plan -d "Enable plan mode"
complete -c cortex -l bypass -d "Enable bypass safeguards mode (auto-approve all tool calls)"
complete -c cortex -l dangerously-allow-all-tool-calls -d "Enable bypass safeguards mode (auto-approve all tool calls)"
complete -c cortex -l auto-accept-plans -d "Auto-accept plan mode requests and confirmations without prompting"
complete -c cortex -l profile -d "Apply a profile configuration (from ~/.snowflake/cortex/profiles/)"
complete -c cortex -l resume -s r -d "Open the resume menu on startup or immediately resume a session by session ID"
complete -c cortex -l continue -d "Resume the most recent session"
complete -c cortex -l session-name -d "Name for the new session (ignored when resuming)"
complete -c cortex -l output-format -d "Output format: 'stream-json' for JSON streaming output"
complete -c cortex -l print -s p -d "Print a series of chat response and exit (in headless, non-interactive mode)"
complete -c cortex -l config -d "Path to a custom settings.json configuration file (default: ~/.snowflake/cortex/settings.json)"
complete -c cortex -l config-file -d "Path to Snowflake connection config file (connections.toml or config.toml)"
complete -c cortex -l skills -d "Path to a custom skills.json configuration file (default: ~/.snowflake/cortex/skills.json)"
complete -c cortex -l mcp -d "Enable MCP servers (use --no-mcp to disable)"
complete -c cortex -l auto-update -d "Auto-update on launch (use --no-auto-update to disable)"
complete -c cortex -l worktree -d "Create a new worktree with the specified branch name and start session in it"
complete -c cortex -l plugin-dir -d "Plugin directory or GitHub repo (owner/repo, owner/repo#branch, or URL). Can be repeated."
complete -c cortex -l shell -d "Shell executor for commands: 'powershell', 'cmd', or 'bash' (default: auto-detect; on Windows defaults to powershell)"
complete -c cortex -l version -s V -d "Show version"

# Commands
complete -c cortex -n "__fish_use_subcommand" -a "mcp" -d "Manage MCP servers"
complete -c cortex -n "__fish_use_subcommand" -a "profile" -d "Manage profiles"
complete -c cortex -n "__fish_use_subcommand" -a "skill" -d "Manage skill directories"
complete -c cortex -n "__fish_use_subcommand" -a "resume" -d "Resume a previous session"
complete -c cortex -n "__fish_use_subcommand" -a "update" -d "Update to latest version"
complete -c cortex -n "__fish_use_subcommand" -a "versions" -d "List locally installed versions"
complete -c cortex -n "__fish_use_subcommand" -a "worktree" -d "Manage git worktrees"
complete -c cortex -n "__fish_use_subcommand" -a "completion" -d "Shell completion scripts"
complete -c cortex -n "__fish_use_subcommand" -a "connections" -d "Manage Snowflake connections"
complete -c cortex -n "__fish_use_subcommand" -a "search" -d "Search operations"
complete -c cortex -n "__fish_use_subcommand" -a "reflect" -d "Validate semantic model"
complete -c cortex -n "__fish_use_subcommand" -a "artifact" -d "Artifact operations"
complete -c cortex -n "__fish_use_subcommand" -a "analyst" -d "Cortex Analyst operations"
complete -c cortex -n "__fish_use_subcommand" -a "env" -d "Environment detection"
complete -c cortex -n "__fish_use_subcommand" -a "attach" -d "Attach to a background agent"
