function __tuist_should_offer_completions_for -a expected_commands -a expected_positional_index
    set -l unparsed_tokens (__tuist_tokens -pc)
    set -l positional_index 0
    set -l commands

    switch $unparsed_tokens[1]
    case 'tuist'
        __tuist_parse_subcommand 0 'h/help'
        switch $unparsed_tokens[1]
        case 'init'
            __tuist_parse_subcommand 0 'p/path=' 'h/help'
        case 'hash'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'cache'
                __tuist_parse_subcommand 0 'p/path=' 'c/configuration=' 'h/help'
            case 'selective-testing'
                __tuist_parse_subcommand -r 1 'p/path=' 'h/help'
            end
        case 'cache'
            __tuist_parse_subcommand -r 1 'p/path=' 'c/configuration=' 'external-only' 'no-external-only' 'generate-only' 'no-generate-only' 'print-hashes' 'no-print-hashes' 'h/help'
        case 'clean'
            __tuist_parse_subcommand -r 1 'remote' 'no-remote' 'p/path=' 'h/help'
        case 'dump'
            __tuist_parse_subcommand 1 'p/path=' 'h/help'
        case 'edit'
            __tuist_parse_subcommand 0 'p/path=' 'P/permanent' 'no-permanent' 'o/only-current-directory' 'no-only-current-directory' 'h/help'
        case 'generate'
            __tuist_parse_subcommand -r 1 'p/path=' 'o/open' 'no-open' 'binary-cache' 'no-binary-cache' 'cache-profile=' 'c/configuration=' 'h/help'
        case 'graph'
            __tuist_parse_subcommand -r 1 't/skip-test-targets' 'no-skip-test-targets' 'd/skip-external-dependencies' 'no-skip-external-dependencies' 'l/platform=' 'f/format=' 'open' 'no-open' 'a/algorithm=' 'p/path=' 'o/output-path=' 'h/help'
        case 'install'
            __tuist_parse_subcommand -r 1 'p/path=' 'u/update' 'no-update' 'h/help'
        case 'migration'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'settings-to-xcconfig'
                __tuist_parse_subcommand 0 'p/xcodeproj-path=' 'x/xcconfig-path=' 't/target=' 'h/help'
            case 'check-empty-settings'
                __tuist_parse_subcommand 0 'p/xcodeproj-path=' 't/target=' 'h/help'
            case 'list-targets'
                __tuist_parse_subcommand 0 'p/xcodeproj-path=' 'h/help'
            end
        case 'plugin'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'archive'
                __tuist_parse_subcommand 0 'p/path=' 'h/help'
            case 'build'
                __tuist_parse_subcommand 0 'c/configuration=' 'p/path=' 'build-tests' 'no-build-tests' 'show-bin-path' 'no-show-bin-path' 'targets=' 'products=' 'h/help'
            case 'run'
                __tuist_parse_subcommand -r 2 'c/configuration=' 'p/path=' 'build-tests' 'no-build-tests' 'skip-build' 'no-skip-build' 'h/help'
            case 'test'
                __tuist_parse_subcommand 0 'c/configuration=' 'p/path=' 'build-tests' 'no-build-tests' 'test-products=' 'h/help'
            end
        case 'registry'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'setup'
                __tuist_parse_subcommand 0 'p/path=' 'h/help'
            case 'login'
                __tuist_parse_subcommand 0 'p/path=' 'h/help'
            case 'logout'
                __tuist_parse_subcommand 0 'p/path=' 'h/help'
            end
        case 'run'
            __tuist_parse_subcommand -r 2 'generate' 'no-generate' 'clean' 'no-clean' 'p/path=' 'C/configuration=' 'device=' 'o/os=' 'rosetta' 'h/help'
        case 'scaffold'
            __tuist_parse_subcommand 1 'json' 'no-json' 'p/path=' 'h/help'
            switch $unparsed_tokens[1]
            case 'list'
                __tuist_parse_subcommand 0 'json' 'no-json' 'p/path=' 'h/help'
            end
        case 'setup'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'cache'
                __tuist_parse_subcommand 0 'p/path=' 'h/help'
            end
        case 'test'
            __tuist_parse_subcommand -r 2 'c/clean' 'no-clean' 'n/no-upload' 'no-no-upload' 'p/path=' 'd/device=' 'platform=' 'o/os=' 'rosetta' 'no-rosetta' 'C/configuration=' 'skip-ui-tests' 'no-skip-ui-tests' 'skip-unit-tests' 'no-skip-unit-tests' 'T/result-bundle-path=' 'derived-data-path=' 'retry-count=' 'test-plan=' 'test-targets=' 'skip-test-targets=' 'filter-configurations=' 'skip-configurations=' 'binary-cache' 'no-binary-cache' 'selective-testing' 'no-selective-testing' 'generate-only' 'no-generate-only' 'without-building' 'no-without-building' 'build-only' 'no-build-only' 'h/help'
        case 'inspect'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'implicit-imports'
                __tuist_parse_subcommand 0 'p/path=' 'h/help'
            case 'redundant-imports'
                __tuist_parse_subcommand 0 'p/path=' 'h/help'
            case 'build'
                __tuist_parse_subcommand 0 'p/path=' 'derived-data-path=' 'h/help'
            case 'bundle'
                __tuist_parse_subcommand 1 'json' 'no-json' 'p/path=' 'h/help'
            case 'test'
                __tuist_parse_subcommand 1 'p/path=' 'derived-data-path=' 'h/help'
            end
        case 'xcodebuild'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'test'
                __tuist_parse_subcommand -r 1 'h/help'
            case 'test-without-building'
                __tuist_parse_subcommand -r 1 'h/help'
            case 'build'
                __tuist_parse_subcommand -r 1 'h/help'
            case 'build-for-testing'
                __tuist_parse_subcommand -r 1 'h/help'
            case 'archive'
                __tuist_parse_subcommand -r 1 'h/help'
            case 'xcode-build-command-reorderer'
                __tuist_parse_subcommand -r 1 'h/help'
            end
        case 'share'
            __tuist_parse_subcommand -r 1 'p/path=' 'C/configuration=' 'platforms=' 'derived-data-path=' 'json' 'no-json' 'track=' 'h/help'
        case 'mcp'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'setup'
                __tuist_parse_subcommand 0 'h/help'
                switch $unparsed_tokens[1]
                case 'claude'
                    __tuist_parse_subcommand 0 'h/help'
                case 'claude-code'
                    __tuist_parse_subcommand 0 'h/help'
                case 'cursor'
                    __tuist_parse_subcommand 0 'p/path=' 'global' 'h/help'
                case 'zed'
                    __tuist_parse_subcommand 0 'p/path=' 'global' 'h/help'
                case 'vscode'
                    __tuist_parse_subcommand 0 'p/path=' 'global' 'h/help'
                end
            end
        case 'account'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'tokens'
                __tuist_parse_subcommand 0 'h/help'
                switch $unparsed_tokens[1]
                case 'create'
                    __tuist_parse_subcommand 1 's/scopes=' 'n/name=' 'e/expires=' 'projects=' 'path=' 'h/help'
                case 'list'
                    __tuist_parse_subcommand 1 'p/path=' 'json' 'h/help'
                case 'revoke'
                    __tuist_parse_subcommand 2 'p/path=' 'h/help'
                end
            case 'update'
                __tuist_parse_subcommand 1 'handle=' 'p/path=' 'h/help'
            end
        case 'project'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'show'
                __tuist_parse_subcommand 1 'web' 'no-web' 'p/path=' 'h/help'
            case 'create'
                __tuist_parse_subcommand 1 'p/path=' 'h/help'
            case 'list'
                __tuist_parse_subcommand 0 'json' 'no-json' 'p/path=' 'h/help'
            case 'delete'
                __tuist_parse_subcommand 1 'p/path=' 'h/help'
            case 'update'
                __tuist_parse_subcommand 1 'default-branch=' 'visibility=' 'p/path=' 'h/help'
            end
        case 'bundle'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'list'
                __tuist_parse_subcommand 0 'P/project=' 'p/path=' 'git-branch=' 'json' 'no-json' 'h/help'
            case 'show'
                __tuist_parse_subcommand 1 'P/project=' 'p/path=' 'json' 'no-json' 'h/help'
            end
        case 'organization'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'create'
                __tuist_parse_subcommand 1 'p/path=' 'h/help'
            case 'list'
                __tuist_parse_subcommand 0 'json' 'no-json' 'p/path=' 'h/help'
            case 'delete'
                __tuist_parse_subcommand 1 'p/path=' 'h/help'
            case 'show'
                __tuist_parse_subcommand 1 'json' 'no-json' 'p/path=' 'h/help'
            case 'invite'
                __tuist_parse_subcommand 2 'p/path=' 'h/help'
            case 'remove'
                __tuist_parse_subcommand 0 'h/help'
                switch $unparsed_tokens[1]
                case 'invite'
                    __tuist_parse_subcommand 2 'p/path=' 'h/help'
                case 'member'
                    __tuist_parse_subcommand 2 'p/path=' 'h/help'
                case 'sso'
                    __tuist_parse_subcommand 1 'p/path=' 'h/help'
                end
            case 'update'
                __tuist_parse_subcommand 0 'h/help'
                switch $unparsed_tokens[1]
                case 'member'
                    __tuist_parse_subcommand 2 'role=' 'p/path=' 'h/help'
                case 'sso'
                    __tuist_parse_subcommand 1 'provider=' 'o/organization-id=' 'p/path=' 'h/help'
                end
            case 'billing'
                __tuist_parse_subcommand 1 'p/path=' 'h/help'
            end
        case 'auth'
            __tuist_parse_subcommand 0 'h/help'
            switch $unparsed_tokens[1]
            case 'login'
                __tuist_parse_subcommand 0 'email=' 'password=' 'p/path=' 'h/help'
            case 'logout'
                __tuist_parse_subcommand 0 'p/path=' 'h/help'
            case 'whoami'
                __tuist_parse_subcommand 0 'p/path=' 'h/help'
            end
        case 'version'
            __tuist_parse_subcommand 0 'h/help'
        case 'help'
            __tuist_parse_subcommand -r 1 
        end
    end

    test "$commands" = "$expected_commands" -a \( -z "$expected_positional_index" -o "$expected_positional_index" -eq "$positional_index" \)
end

function __tuist_tokens
    if test (string split -m 1 -f 1 -- . "$FISH_VERSION") -gt 3
        commandline --tokens-raw $argv
    else
        commandline -o $argv
    end
end

function __tuist_parse_subcommand -S
    argparse -s r -- $argv
    set -l positional_count $argv[1]
    set -l option_specs $argv[2..]

    set -a commands $unparsed_tokens[1]
    set -e unparsed_tokens[1]

    set positional_index 0

    while true
        argparse -sn "$commands" $option_specs -- $unparsed_tokens 2> /dev/null
        set unparsed_tokens $argv
        set positional_index (math $positional_index + 1)
        if test (count $unparsed_tokens) -eq 0 -o \( -z "$_flag_r" -a "$positional_index" -gt "$positional_count" \)
            return 0
        end
        set -e unparsed_tokens[1]
    end
end

function __tuist_complete_directories
    set -l token (commandline -t)
    string match -- '*/' $token
    set -l subdirs $token*/
    printf '%s\n' $subdirs
end

function __tuist_custom_completion
    set -x SAP_SHELL fish
    set -x SAP_SHELL_VERSION $FISH_VERSION

    set -l tokens (__tuist_tokens -p)
    if test -z (__tuist_tokens -t)
        set -l index (count (__tuist_tokens -pc))
        set tokens $tokens[..$index] \'\' $tokens[(math $index + 1)..]
    end
    command $tokens[1] $argv $tokens
end

complete -c 'tuist' -f
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'init' -d 'Get started with Tuist in your Xcode project or create a generated project.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'hash' -d 'Utilities to debug the hashing logic used by features like binary caching or selective testing.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'cache' -d 'Warms the local and remote cache.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'clean' -d 'Clean all the artifacts stored locally'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'dump' -d 'Outputs the manifest as a JSON'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'edit' -d 'Generates a temporary project to edit the project in the current directory'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'generate' -d 'Generates an Xcode workspace to start working on the project.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'graph' -d 'Generates a graph from the workspace or project in the current directory'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'install' -d 'Installs any remote content (e.g. dependencies) necessary to interact with the project.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'migration' -d 'A set of utilities to assist in the migration of Xcode projects to Tuist.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'plugin' -d 'A set of commands for plugin\'s management.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'registry' -d 'A set of commands to interact with the Tuist Registry.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'run' -d 'Runs a scheme or target in the project'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'scaffold' -d 'Generates new project based on a template'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'setup' -d 'Commands to set up and configure Tuist services'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'test' -d 'Tests a project'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'inspect' -d 'Inspect your project to identify issues such as implicit or redundant dependencies.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'xcodebuild' -d 'tuist xcodebuild extends the xcodebuild CLI with server capabilities such as selective testing or analytics.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'share' -d 'Generate a link to share your app.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'mcp' -d 'Commands for interfacing with Tuist\'s MCP server'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'account' -d 'A set of commands to manage your Tuist account'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'project' -d 'A set of commands to manage your Tuist projects.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'bundle' -d 'A set of commands to manage your project bundles.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'organization' -d 'A set of commands to manage your Tuist organizations.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'auth' -d 'Manage authentication'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'version' -d 'Outputs the current version of tuist'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist" 1' -fa 'help' -d 'Show subcommand help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist init"' -l 'path' -s 'p' -d 'The path to the directory from where to start. (env: TUIST_INIT_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist init"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist hash"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist hash" 1' -fa 'cache' -d 'Returns the hashes that will be used to persist binaries of the graph in its current state to the cache.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist hash" 1' -fa 'selective-testing' -d 'Returns the hashes that will be used to persist targets\' test results to select tests in future test runs.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist hash cache"' -l 'path' -s 'p' -d 'The path to the directory that contains the project whose targets will be cached. (env: TUIST_HASH_CACHE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist hash cache"' -l 'configuration' -s 'c' -d 'The project configuration the cache binaries will be bound to. (env: TUIST_HASH_CACHE_CONFIGURATION)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist hash cache"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist hash selective-testing"' -l 'path' -s 'p' -d 'The path to the directory that contains the project whose tests will run selectively. (env: TUIST_HASH_CACHE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist hash selective-testing"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist cache"' -l 'path' -s 'p' -d 'The path to the directory that contains the project whose targets will be cached. (env: TUIST_CACHE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist cache"' -l 'configuration' -s 'c' -d 'Configuration to use for binary caching. (env: TUIST_CACHE_CONFIGURATION)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist cache"' -l 'external-only' -d 'If passed, the command doesn\'t cache the targets passed in the `--targets` argument, but only their dependencies (env: TUIST_CACHE_EXTERNAL_ONLY)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist cache"' -l 'no-external-only' -d 'If passed, the command doesn\'t cache the targets passed in the `--targets` argument, but only their dependencies (env: TUIST_CACHE_EXTERNAL_ONLY)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist cache"' -l 'generate-only' -d 'When passed, it generates the project and skips warming the cache. This is useful for debugging purposes. (env: TUIST_CACHE_GENERATE_ONLY)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist cache"' -l 'no-generate-only' -d 'When passed, it generates the project and skips warming the cache. This is useful for debugging purposes. (env: TUIST_CACHE_GENERATE_ONLY)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist cache"' -l 'print-hashes' -d 'When passed, the hashes of the cacheable frameworks in the given project are printed. (env: TUIST_CACHE_PRINT_HASHES)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist cache"' -l 'no-print-hashes' -d 'When passed, the hashes of the cacheable frameworks in the given project are printed. (env: TUIST_CACHE_PRINT_HASHES)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist cache"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist clean" 1' -fka 'plugins generatedAutomationProjects projectDescriptionHelpers manifests editProjects runs binaries selectiveTests dependencies'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist clean"' -l 'remote' -d 'Clean the remote cache (env: TUIST_CLEAN_REMOTE)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist clean"' -l 'no-remote' -d 'Clean the remote cache (env: TUIST_CLEAN_REMOTE)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist clean"' -l 'path' -s 'p' -d 'The path to the directory that contains the project that should be cleaned. (env: TUIST_CLEAN_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist clean"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist dump"' -l 'path' -s 'p' -d 'The path to the folder where the manifest is (env: TUIST_DUMP_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist dump" 1' -fka 'project workspace config template plugin package'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist dump"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist edit"' -l 'path' -s 'p' -d 'The path to the directory whose project will be edited (env: TUIST_EDIT_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist edit"' -l 'permanent' -s 'P' -d 'It creates the project in the current directory or the one indicated by -p and doesn\'t block the process (env: TUIST_EDIT_PERMANENT)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist edit"' -l 'no-permanent' -d 'It creates the project in the current directory or the one indicated by -p and doesn\'t block the process (env: TUIST_EDIT_PERMANENT)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist edit"' -l 'only-current-directory' -s 'o' -d 'It only includes the manifest in the current directory. (env: TUIST_EDIT_ONLY_CURRENT_DIRECTORY)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist edit"' -l 'no-only-current-directory' -d 'It only includes the manifest in the current directory. (env: TUIST_EDIT_ONLY_CURRENT_DIRECTORY)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist edit"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist generate"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_GENERATE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist generate"' -l 'open' -s 'o' -d 'Don\'t open the project after generating it. (env: TUIST_GENERATE_OPEN)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist generate"' -l 'no-open' -d 'Don\'t open the project after generating it. (env: TUIST_GENERATE_OPEN)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist generate"' -l 'binary-cache' -d 'Ignore binary cache and use sources only. (env: TUIST_GENERATE_BINARY_CACHE)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist generate"' -l 'no-binary-cache' -d 'Ignore binary cache and use sources only. (env: TUIST_GENERATE_BINARY_CACHE)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist generate"' -l 'cache-profile' -d 'Binary cache profile to use: only-external, all-possible, none, or a custom profile name. Defaults to the profile configured in Tuist.swift, or \'only-external\' if not configured. (env: TUIST_GENERATE_CACHE_PROFILE)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist generate"' -l 'configuration' -s 'c' -d 'Configuration to generate for.' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist generate"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -s 't' -l 'skip-test-targets' -d 'Skip Test targets during graph rendering. (env: TUIST_GRAPH_SKIP_TEST_TARGETS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -l 'no-skip-test-targets' -d 'Skip Test targets during graph rendering. (env: TUIST_GRAPH_SKIP_TEST_TARGETS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -s 'd' -l 'skip-external-dependencies' -d 'Skip external dependencies. (env: TUIST_GRAPH_SKIP_EXTERNAL_DEPENDENCIES)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -l 'no-skip-external-dependencies' -d 'Skip external dependencies. (env: TUIST_GRAPH_SKIP_EXTERNAL_DEPENDENCIES)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -s 'l' -l 'platform' -d 'A platform to filter. Only targets for this platform will be showed in the graph. Available platforms: ios, macos, tvos, watchos (env: TUIST_GRAPH_PLATFORM)' -rfka 'ios macos tvos watchos visionos'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -s 'f' -l 'format' -d 'Available formats: dot, json, png, svg (env: TUIST_GRAPH_FORMAT)' -rfka 'dot json legacyJSON png svg'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -l 'open' -d 'Don\'t open the file after generating it. (env: TUIST_GRAPH_OPEN)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -l 'no-open' -d 'Don\'t open the file after generating it. (env: TUIST_GRAPH_OPEN)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -s 'a' -l 'algorithm' -d 'Available formats: dot, neato, twopi, circo, fdp, sfdp, patchwork (env: TUIST_GRAPH_LAYOUT_ALGORITHM)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -l 'path' -s 'p' -d 'The path to the directory that contains the project whose targets will be cached. (env: TUIST_GRAPH_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -l 'output-path' -s 'o' -d 'The path where the graph will be generated. (env: TUIST_GRAPH_OUTPUT_PATH)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist graph"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist install"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_INSTALL_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist install"' -l 'update' -s 'u' -d 'Instead of simple install, update external content when available. (env: TUIST_INSTALL_UPDATE)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist install"' -l 'no-update' -d 'Instead of simple install, update external content when available. (env: TUIST_INSTALL_UPDATE)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist install"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration" 1' -fa 'settings-to-xcconfig' -d 'It extracts the build settings from a project or a target into an xcconfig file.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration" 1' -fa 'check-empty-settings' -d 'It checks if the build settings of a project or target are empty. Otherwise it exits unsuccessfully.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration" 1' -fa 'list-targets' -d 'It lists the targets of a project sorted by number of dependencies.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration settings-to-xcconfig"' -s 'p' -l 'xcodeproj-path' -d 'The path to the Xcode project (env: TUIST_MIGRATION_SETTINGS_TO_XCCONFIG_XCODEPROJ_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration settings-to-xcconfig"' -s 'x' -l 'xcconfig-path' -d 'The path to the .xcconfig file where build settings will be extracted. (env: TUIST_MIGRATION_SETTINGS_TO_XCCONFIG_XCCONFIG_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration settings-to-xcconfig"' -l 'target' -s 't' -d 'The name of the target whose build settings will be extracted. When not passed, it extracts the build settings of the project. (env: TUIST_MIGRATION_SETTINGS_TO_XCCONFIG_TARGET)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration settings-to-xcconfig"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration check-empty-settings"' -s 'p' -l 'xcodeproj-path' -d 'The path to the Xcode project (env: TUIST_MIGRATION_CHECK_EMPTY_SETTINGS_XCODEPROJ_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration check-empty-settings"' -l 'target' -s 't' -d 'The name of the target whose build settings will be checked. When not passed, it checks the build settings of the project. (env: TUIST_MIGRATION_CHECK_EMPTY_SETTINGS_TARGET)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration check-empty-settings"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration list-targets"' -s 'p' -l 'xcodeproj-path' -d 'The path to the Xcode project (env: TUIST_MIGRATION_LIST_TARGETS_XCODEPROJ_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist migration list-targets"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin" 1' -fa 'archive' -d 'Archives a plugin into a NameOfPlugin.tuist-plugin.zip.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin" 1' -fa 'build' -d 'Builds a plugin.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin" 1' -fa 'run' -d 'Runs a plugin.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin" 1' -fa 'test' -d 'Tests a plugin.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin archive"' -l 'path' -s 'p' -d 'The path to the directory that contains the definition of the plugin. (env: TUIST_PLUGIN_ARCHIVE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin archive"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin build"' -l 'configuration' -s 'c' -d 'Choose configuration (default: debug). (env: TUIST_PLUGIN_OPTIONS_CONFIGURATION)' -rfka 'debug release'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin build"' -l 'path' -s 'p' -d 'The path to the directory that contains the definition of the plugin. (env: TUIST_PLUGIN_OPTIONS_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin build"' -l 'build-tests' -d 'Build both source and test targets. (env: TUIST_PLUGIN_BUILD_BUILD_TESTS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin build"' -l 'no-build-tests' -d 'Build both source and test targets. (env: TUIST_PLUGIN_BUILD_BUILD_TESTS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin build"' -l 'show-bin-path' -d 'Print the binary output path. (env: TUIST_PLUGIN_BUILD_SHOW_BIN_PATH)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin build"' -l 'no-show-bin-path' -d 'Print the binary output path. (env: TUIST_PLUGIN_BUILD_SHOW_BIN_PATH)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin build"' -l 'targets' -d 'Build the specified targets. (env: TUIST_PLUGIN_BUILD_TARGETS)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin build"' -l 'products' -d 'Build the specified products. (env: TUIST_PLUGIN_BUILD_PRODUCTS)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin build"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin run"' -l 'configuration' -s 'c' -d 'Choose configuration (default: debug). (env: TUIST_PLUGIN_OPTIONS_CONFIGURATION)' -rfka 'debug release'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin run"' -l 'path' -s 'p' -d 'The path to the directory that contains the definition of the plugin. (env: TUIST_PLUGIN_OPTIONS_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin run"' -l 'build-tests' -d 'Build both source and test targets. (env: TUIST_PLUGIN_RUN_BUILD_TESTS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin run"' -l 'no-build-tests' -d 'Build both source and test targets. (env: TUIST_PLUGIN_RUN_BUILD_TESTS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin run"' -l 'skip-build' -d 'Skip building the plugin. (env: TUIST_PLUGIN_RUN_SKIP_BUILD)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin run"' -l 'no-skip-build' -d 'Skip building the plugin. (env: TUIST_PLUGIN_RUN_SKIP_BUILD)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin run"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin test"' -l 'configuration' -s 'c' -d 'Choose configuration (default: debug). (env: TUIST_PLUGIN_OPTIONS_CONFIGURATION)' -rfka 'debug release'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin test"' -l 'path' -s 'p' -d 'The path to the directory that contains the definition of the plugin. (env: TUIST_PLUGIN_OPTIONS_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin test"' -l 'build-tests' -d 'Build both source and test targets. (env: TUIST_PLUGIN_TEST_BUILD_TESTS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin test"' -l 'no-build-tests' -d 'Build both source and test targets. (env: TUIST_PLUGIN_TEST_BUILD_TESTS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin test"' -l 'test-products' -d 'Test the specified products. (env: TUIST_PLUGIN_TEST_TEST_PRODUCTS)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist plugin test"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist registry"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist registry" 1' -fa 'setup' -d 'Set up the Tuist Registry.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist registry" 1' -fa 'login' -d 'Log in to the registry.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist registry" 1' -fa 'logout' -d 'Log out of the registry.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist registry setup"' -l 'path' -s 'p' -d 'The path to the directory that contains the project to set up the registry for. (env: TUIST_REGISTRY_SETUP_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist registry setup"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist registry login"' -l 'path' -s 'p' -d 'The path to the directory that contains the project to which registry you want to log in. (env: TUIST_REGISTRY_LOGIN_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist registry login"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist registry logout"' -l 'path' -s 'p' -d 'The path to the directory that contains the project to which registry you want to log out of. (env: TUIST_REGISTRY_LOGOUT_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist registry logout"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist run"' -l 'generate' -d 'Force the generation of the project before running. (env: TUIST_RUN_GENERATE)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist run"' -l 'no-generate' -d 'Force the generation of the project before running. (env: TUIST_RUN_GENERATE)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist run"' -l 'clean' -d 'When passed, it cleans the project before running. (env: TUIST_RUN_CLEAN)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist run"' -l 'no-clean' -d 'When passed, it cleans the project before running. (env: TUIST_RUN_CLEAN)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist run"' -l 'path' -s 'p' -d 'The path to the directory that contains the project with the target or scheme to be run.' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist run"' -l 'configuration' -s 'C' -d 'The configuration to be used when building the scheme.' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist run"' -l 'device' -d 'The simulator or physical device name to run the target, scheme, or preview on.' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist run"' -l 'os' -s 'o' -d 'The OS version of the simulator. (env: TUIST_RUN_OS)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist run"' -l 'rosetta' -d 'When passed, append arch=x86_64 to the \'destination\' to run simulator in a Rosetta mode.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist run"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist scaffold"' -l 'json' -d 'The output in JSON format (env: TUIST_SCAFFOLD_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist scaffold"' -l 'no-json' -d 'The output in JSON format (env: TUIST_SCAFFOLD_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist scaffold"' -l 'path' -s 'p' -d 'The path to the folder where the template will be generated (Default: Current directory) (env: TUIST_SCAFFOLD_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist scaffold"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist scaffold" 1' -fa 'list' -d 'Lists available scaffold templates'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist scaffold list"' -l 'json' -d 'The output in JSON format (env: TUIST_SCAFFOLD_LIST_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist scaffold list"' -l 'no-json' -d 'The output in JSON format (env: TUIST_SCAFFOLD_LIST_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist scaffold list"' -l 'path' -s 'p' -d 'The path where you want to list templates from (env: TUIST_SCAFFOLD_LIST_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist scaffold list"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist setup"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist setup" 1' -fa 'cache' -d 'Set up the Tuist Xcode cache'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist setup cache"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project.' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist setup cache"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'clean' -s 'c' -d 'When passed, it cleans the project before testing it. (env: TUIST_TEST_CLEAN)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-clean' -d 'When passed, it cleans the project before testing it. (env: TUIST_TEST_CLEAN)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-upload' -s 'n' -d 'When passed, the result necessary for test selection is not persisted to the server. (env: TUIST_TEST_NO_UPLOAD)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-no-upload' -d 'When passed, the result necessary for test selection is not persisted to the server. (env: TUIST_TEST_NO_UPLOAD)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'path' -s 'p' -d 'The path to the directory that contains the project to be tested. (env: TUIST_TEST_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'device' -s 'd' -d 'Test on a specific device. (env: TUIST_TEST_DEVICE)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'platform' -d 'Test on a specific platform. (env: TUIST_TEST_PLATFORM)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'os' -s 'o' -d 'Test with a specific version of the OS. (env: TUIST_TEST_OS)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'rosetta' -d 'When passed, append arch=x86_64 to the \'destination\' to run simulator in a Rosetta mode. (env: TUIST_TEST_ROSETTA)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-rosetta' -d 'When passed, append arch=x86_64 to the \'destination\' to run simulator in a Rosetta mode. (env: TUIST_TEST_ROSETTA)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'configuration' -s 'C' -d 'The configuration to be used when testing the scheme. (env: TUIST_TEST_CONFIGURATION)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'skip-ui-tests' -d 'When passed, it skips testing UI Tests targets. (env: TUIST_TEST_SKIP_UITESTS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-skip-ui-tests' -d 'When passed, it skips testing UI Tests targets. (env: TUIST_TEST_SKIP_UITESTS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'skip-unit-tests' -d 'When passed, it skips testing Unit Tests targets. (env: TUIST_TEST_SKIP_UNITTESTS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-skip-unit-tests' -d 'When passed, it skips testing Unit Tests targets. (env: TUIST_TEST_SKIP_UNITTESTS)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'result-bundle-path' -s 'T' -d 'Path where test result bundle will be saved. (env: TUIST_TEST_RESULT_BUNDLE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'derived-data-path' -d '[Deprecated] Overrides the folder that should be used for derived data when testing a project. (env: TUIST_TEST_DERIVED_DATA_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'retry-count' -d '[Deprecated] Tests will retry <number> of times until success. Example: if 1 is specified, the test will be retried at most once, hence it will run up to 2 times. (env: TUIST_TEST_RETRY_COUNT)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'test-plan' -d 'The test plan to run. (env: TUIST_TEST_TEST_PLAN)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'test-targets' -d 'The list of test identifiers you want to test. Expected format is TestTarget[/TestClass[/TestMethod]]. It is applied before --skip-testing (env: TUIST_TEST_TEST_TARGETS)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'skip-test-targets' -d 'The list of test identifiers you want to skip testing. Expected format is TestTarget[/TestClass[/TestMethod]]. (env: TUIST_TEST_SKIP_TEST_TARGETS)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'filter-configurations' -d 'The list of configurations you want to test. It is applied before --skip-configuration (env: TUIST_TEST_CONFIGURATIONS)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'skip-configurations' -d 'The list of configurations you want to skip testing. (env: TUIST_TEST_SKIP_CONFIGURATIONS)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'binary-cache' -d 'Ignore binary cache and use sources only. (env: TUIST_TEST_BINARY_CACHE)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-binary-cache' -d 'Ignore binary cache and use sources only. (env: TUIST_TEST_BINARY_CACHE)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'selective-testing' -d 'When --no-selective-testing is passed, tuist runs all tests without using selective testing. (env: TUIST_TEST_SELECTIVE_TESTING)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-selective-testing' -d 'When --no-selective-testing is passed, tuist runs all tests without using selective testing. (env: TUIST_TEST_SELECTIVE_TESTING)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'generate-only' -d 'When passed, it generates the project and skips testing. This is useful for debugging purposes. (env: TUIST_TEST_GENERATE_ONLY)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-generate-only' -d 'When passed, it generates the project and skips testing. This is useful for debugging purposes. (env: TUIST_TEST_GENERATE_ONLY)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'without-building' -d 'When passed, run the tests without building. (env: TUIST_TEST_WITHOUT_BUILDING)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-without-building' -d 'When passed, run the tests without building. (env: TUIST_TEST_WITHOUT_BUILDING)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'build-only' -d 'When passed, build the tests, but don\'t run them (env: TUIST_TEST_BUILD_ONLY)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -l 'no-build-only' -d 'When passed, build the tests, but don\'t run them (env: TUIST_TEST_BUILD_ONLY)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist test"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect" 1' -fa 'implicit-imports' -d 'Find implicit imports in Tuist projects failing when cases are found.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect" 1' -fa 'redundant-imports' -d 'Find redundant imports in Tuist projects failing when cases are found.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect" 1' -fa 'build' -d 'Inspects the latest build.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect" 1' -fa 'bundle' -d 'Inspects an app bundle. The app bundle has to be either `.app`, `.xcarchive` or `.ipa`.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect" 1' -fa 'test' -d 'Inspects the latest test results.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect implicit-imports"' -l 'path' -s 'p' -d 'The path to the directory that contains the project. (env: TUIST_LINT_IMPLICIT_DEPENDENCIES_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect implicit-imports"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect redundant-imports"' -l 'path' -s 'p' -d 'The path to the directory that contains the project. (env: TUIST_LINT_REDUNDANT_DEPENDENCIES_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect redundant-imports"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect build"' -l 'path' -s 'p' -d 'The path to the directory that contains the project to inspect the latest build for. (env: TUIST_INSPECT_BUILD_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect build"' -l 'derived-data-path' -d 'The path to the directory containing the project\'s derived data artifacts. (env: TUIST_INSPECT_BUILD_DERIVED_DATA_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect build"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect bundle" 1' -fa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect bundle"' -l 'json' -d 'The output in JSON format. (env: TUIST_INSPECT_BUNDLE_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect bundle"' -l 'no-json' -d 'The output in JSON format. (env: TUIST_INSPECT_BUNDLE_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect bundle"' -l 'path' -s 'p' -d 'The path to the directory that contains the project associated with the inspected bundle. (env: TUIST_INSPECT_BUNDLE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect bundle"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect test"' -l 'path' -s 'p' -d 'The path to the directory that contains the project to inspect the latest test results for. (env: TUIST_INSPECT_TEST_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect test"' -l 'derived-data-path' -d 'The path to the directory containing the project\'s derived data artifacts. (env: TUIST_INSPECT_TEST_DERIVED_DATA_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect test" 1' -fa '(for p in (string match -e -- \'*/\' (commandline -t);or printf \n)*.\'xcresult\';printf %s\n $p;end;__fish_complete_directories (commandline -t) \'\')'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist inspect test"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild" 1' -fa 'test' -d 'tuist xcodebuild test extends the xcodebuild CLI test action with insights and selective testing capabilities.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild" 1' -fa 'test-without-building' -d 'tuist xcodebuild test-without-building extends the xcodebuild CLI test action with insights and selective testing capabilities.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild" 1' -fa 'build' -d 'tuist xcodebuild build extends the xcodebuild CLI build action with insights.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild" 1' -fa 'build-for-testing' -d 'tuist xcodebuild build-for-testing extends the xcodebuild CLI build-for-testing action with insights.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild" 1' -fa 'archive' -d 'tuist xcodebuild archive extends the xcodebuild CLI archive action with insights.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild" 1' -fa 'xcode-build-command-reorderer' -d ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild test"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild test-without-building"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild build"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild build-for-testing"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild archive"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist xcodebuild xcode-build-command-reorderer"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist share"' -l 'path' -s 'p' -d 'The path to the directory that contains a Tuist or Xcode project with a buildable scheme that can output runnable artifacts.' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist share"' -l 'configuration' -s 'C' -d 'The configuration of the app to share. Ignored when the app paths are passed directly. (env: TUIST_SHARE_CONFIGURATION)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist share"' -l 'platforms' -d 'The platforms (iOS, tvOS, visionOS, watchOS or macOS) to share the app for. Ignored when the app paths are passed directly. (env: TUIST_SHARE_PLATFORM)' -rfka 'iOS tvOS macOS visionOS watchOS'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist share"' -l 'derived-data-path' -d 'The derived data path to find the apps in. When absent, the system-configured one. (env: TUIST_SHARE_DERIVED_DATA_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist share"' -l 'json' -d 'The output in JSON format. (env: TUIST_SHARE_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist share"' -l 'no-json' -d 'The output in JSON format. (env: TUIST_SHARE_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist share"' -l 'track' -d 'The track of the preview (e.g., \'beta\', \'nightly\'). (env: TUIST_SHARE_TRACK)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist share"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp" 1' -fa 'setup' -d 'Commands to automate integrating clients with Tuist\'s MCP server'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup" 1' -fa 'claude' -d 'Configure your environment\'s Claude application to point to the Tuist\'s MCP server.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup" 1' -fa 'claude-code' -d 'Setup Claude Code to use Tuist\'s MCP server'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup" 1' -fa 'cursor' -d 'Setup Cursor IDE to use Tuist\'s MCP server'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup" 1' -fa 'zed' -d 'Setup Zed editor to use Tuist\'s MCP server'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup" 1' -fa 'vscode' -d 'Setup VS Code to use Tuist\'s MCP server'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup claude"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup claude-code"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup cursor"' -l 'path' -s 'p' -d 'The path to the directory where the configuration should be created.' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup cursor"' -l 'global' -d 'Configure Cursor globally instead of locally.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup cursor"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup zed"' -l 'path' -s 'p' -d 'The path to the directory where the configuration should be created.' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup zed"' -l 'global' -d 'Configure Zed globally instead of locally.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup zed"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup vscode"' -l 'path' -s 'p' -d 'The path to the directory where the configuration should be created.' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup vscode"' -l 'global' -d 'Configure VS Code globally instead of locally.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist mcp setup vscode"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account" 1' -fa 'tokens' -d 'Manage Tuist account tokens.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account" 1' -fa 'update' -d 'Update account settings.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens" 1' -fa 'create' -d 'Create a new Tuist account token.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens" 1' -fa 'list' -d 'List Tuist account tokens.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens" 1' -fa 'revoke' -d 'Revoke a Tuist account token.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens create"' -l 'scopes' -s 's' -d 'The scopes for the token. (env: TUIST_ACCOUNT_TOKENS_SCOPES)' -rfka 'ci account:members:read account:members:write account:registry:read account:registry:write project:previews:read project:previews:write project:admin:read project:admin:write project:cache:read project:cache:write project:bundles:read project:bundles:write project:tests:read project:tests:write project:builds:read project:builds:write project:runs:read project:runs:write'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens create"' -l 'name' -s 'n' -d 'A unique identifier for the token. Must be 1-32 characters and contain only alphanumeric characters, hyphens, and underscores. (env: TUIST_ACCOUNT_TOKENS_NAME)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens create"' -l 'expires' -s 'e' -d 'When the token should expire. Use format like \'30d\' (days), \'6m\' (months), or \'1y\' (years). If not specified, the token never expires. (env: TUIST_ACCOUNT_TOKENS_EXPIRES)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens create"' -l 'projects' -d 'The project handles to grant the token access to. If not provided, the token has access to all projects. (env: TUIST_ACCOUNT_TOKENS_PROJECTS)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens create"' -l 'path' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ACCOUNT_TOKENS_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens create"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens list"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ACCOUNT_TOKENS_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens list"' -l 'json' -d 'Output the result as JSON.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens list"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens revoke"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ACCOUNT_TOKENS_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account tokens revoke"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account update"' -l 'handle' -d 'The new handle.' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account update"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project.' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist account update"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project" 1' -fa 'show' -d 'Show information about the specified project. Use --web flag to open the project in the browser.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project" 1' -fa 'create' -d 'Create a new project.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project" 1' -fa 'list' -d 'List projects you have access to.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project" 1' -fa 'delete' -d 'Delete a Tuist project.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project" 1' -fa 'update' -d 'Update project settings'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project show" 1' -fa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project show"' -l 'web' -d 'Open a project in the browser. (env: TUIST_PROJECT_SHOW_WEB)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project show"' -l 'no-web' -d 'Open a project in the browser. (env: TUIST_PROJECT_SHOW_WEB)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project show"' -l 'path' -s 'p' -d 'The path to the Tuist project. (env: TUIST_PROJECT_SHOW_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project show"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project create" 1' -fa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project create"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_PROJECT_CREATE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project create"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project list"' -l 'json' -d 'The output in JSON format. (env: TUIST_PROJECT_LIST_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project list"' -l 'no-json' -d 'The output in JSON format. (env: TUIST_PROJECT_LIST_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project list"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_PROJECT_LIST_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project list"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project delete" 1' -fa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project delete"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_PROJECT_DELETE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project delete"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project update"' -l 'default-branch' -d 'Set the default branch name for the repository linked to the project.' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project update"' -l 'visibility' -d 'Set the project\'s visibility. When private, only project\'s members have access to the project. Public projects are accessible by anyone.' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project update"' -l 'path' -s 'p' -d 'The path to the Tuist project.' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist project update"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle" 1' -fa 'list' -d 'Lists all the bundles in a project.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle" 1' -fa 'show' -d 'Shows information about a bundle.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle list"' -l 'project' -s 'P' -d 'The full handle of the project. Must be in the format of account-handle/project-handle. If not provided, it will be read from the project\'s Tuist.swift. (env: TUIST_BUNDLE_LIST_FULL_HANDLE)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle list"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_BUNDLE_LIST_PATH)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle list"' -l 'git-branch' -d 'Filter bundles by git branch. (env: TUIST_BUNDLE_LIST_GIT_BRANCH)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle list"' -l 'json' -d 'The output in JSON format. (env: TUIST_BUNDLE_LIST_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle list"' -l 'no-json' -d 'The output in JSON format. (env: TUIST_BUNDLE_LIST_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle list"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle show"' -l 'project' -s 'P' -d 'The full handle of the project. Must be in the format of account-handle/project-handle. If not provided, it will be read from the project\'s Tuist.swift. (env: TUIST_BUNDLE_SHOW_FULL_HANDLE)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle show"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_BUNDLE_SHOW_PATH)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle show"' -l 'json' -d 'The output in JSON format. (env: TUIST_BUNDLE_SHOW_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle show"' -l 'no-json' -d 'The output in JSON format. (env: TUIST_BUNDLE_SHOW_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist bundle show"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization" 1' -fa 'create' -d 'Create a new organization.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization" 1' -fa 'list' -d 'List your organizations.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization" 1' -fa 'delete' -d 'Delete a new organization.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization" 1' -fa 'show' -d 'Show information about the specified organization.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization" 1' -fa 'invite' -d 'Invite a new member to your organization.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization" 1' -fa 'remove' -d 'A set of commands to remove members or cancel pending invitations.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization" 1' -fa 'update' -d 'A set of commands to update the organization.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization" 1' -fa 'billing' -d 'Open billing dashboard for the specified organization.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization create"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_CREATE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization create"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization list"' -l 'json' -d 'The output in JSON format. (env: TUIST_ORGANIZATION_LIST_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization list"' -l 'no-json' -d 'The output in JSON format. (env: TUIST_ORGANIZATION_LIST_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization list"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_LIST_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization list"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization delete" 1' -fa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization delete"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_DELETE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization delete"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization show"' -l 'json' -d 'The output in JSON format. (env: TUIST_ORGANIZATION_SHOW_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization show"' -l 'no-json' -d 'The output in JSON format. (env: TUIST_ORGANIZATION_SHOW_JSON)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization show"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_SHOW_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization show"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization invite"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_INVITE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization invite"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization remove"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization remove" 1' -fa 'invite' -d 'Cancel pending invitation.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization remove" 1' -fa 'member' -d 'Remove a member from your organization.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization remove" 1' -fa 'sso' -d 'Remove the SSO provider for your organization.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization remove invite"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_REMOVE_INVITE_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization remove invite"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization remove member"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_REMOVE_MEMBER_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization remove member"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization remove sso"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_REMOVE_SSO_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization remove sso"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization update"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization update" 1' -fa 'member' -d 'Update a member from your organization.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization update" 1' -fa 'sso' -d 'Update the SSO provider for your organization.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization update member"' -l 'role' -d 'The new member role (env: TUIST_ORGANIZATION_UPDATE_MEMBER_ROLE)' -rfka 'admin user'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization update member"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_UPDATE_MEMBER_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization update member"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization update sso"' -l 'provider' -d 'The SSO provider to use. (env: TUIST_ORGANIZATION_UPDATE_SSO_PROVIDER)' -rfka 'google okta'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization update sso"' -l 'organization-id' -s 'o' -d 'Organization ID for your SSO provider. For Google, this is your Google domain (for example, if your email is tuist@tuist.dev, the domain would be tuist.dev). For Okta, it\'s the organization domain (such as my-org.okta.com) (env: TUIST_ORGANIZATION_UPDATE_SSO_ORGANIZATION_ID)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization update sso"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_UPDATE_SSO_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization update sso"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization billing"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_ORGANIZATION_BILLING_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist organization billing"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth" 1' -fa 'login' -d 'Log in a user'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth" 1' -fa 'logout' -d 'Removes an existing Tuist session.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth" 1' -fa 'whoami' -d 'Display the user\'s email identity currently authenticated and in use.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth login"' -l 'email' -d 'Email to authenticate with. (env: TUIST_AUTH_EMAIL)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth login"' -l 'password' -d 'Password to authenticate with. (env: TUIST_AUTH_PASSWORD)' -rfka ''
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth login"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_AUTH_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth login"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth logout"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_LOGOUT_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth logout"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth whoami"' -l 'path' -s 'p' -d 'The path to the directory or a subdirectory of the project. (env: TUIST_WHOAMI_PATH)' -rfa '(__tuist_complete_directories)'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist auth whoami"' -s 'h' -l 'help' -d 'Show help information.'
complete -c 'tuist' -n '__tuist_should_offer_completions_for "tuist version"' -s 'h' -l 'help' -d 'Show help information.'
